### ISSUE TITLE
installation error: argument is of length zero

### ISSUE THREAD

**Issue by fentouxungui** [hredestig/pcaMethods#9] opened 2019-09-26 08:58 UTC
R version 3.6.1 (2019-07-05)
BiocManager::install(c("AnnotationDbi", "BiocGenerics", "GO.db", "pcaMethods"))
```
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
```
Help!

**Comment by fentouxungui** [comment] 2019-09-26 09:04
solved by:
```shell
conda install -c bioconda bioconductor-pcamethods 
```
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bioconductor-biobase-2.44.0|    r36h516909a_1         2.3 MB  bioconda
    bioconductor-biocgenerics-0.30.0|            r36_1         683 KB  bioconda
    bioconductor-pcamethods-1.76.0|    r36he1b5a44_1         1.1 MB  bioconda
    ------------------------------------------------------------
                                           Total:         4.0 MB
```

**Comment by hredestig** [comment] 2019-11-03 17:35
Closing as can't reproduce and luckily you found a workaround

**Closed as completed by hredestig** 2019-11-03 17:35 UTC
